In [1]:
import numpy as np 
import pandas as pd

## NUMPY

In [10]:
vector = np.array([1,2,3,4,5,6])
matrix = np.array([[1,2,3,4], [5,6,7,8]])
tensor = np.array([[[1,2,3],[1,2,3]], [[5,6,7],[1,2,3]]])

print(tensor)
print(vector.size)
print(matrix.size)
print(matrix.shape)





[[[1 2 3]
  [1 2 3]]

 [[5 6 7]
  [1 2 3]]]
6
8
(2, 4)


In [17]:
zero = np.zeros((2,3))
print(zero)

ones = np.ones((4,5))
print(ones)

full = np.full((4,5),12)
print(full)

random = np.random.random((3,4))
print(random)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]]
[[0.21887619 0.94510165 0.63614741 0.90056089]
 [0.5685487  0.60364    0.51453157 0.70963839]
 [0.70820878 0.03130225 0.59434856 0.23510387]]


In [30]:
arr = np.array([1,2,3,4,5,6,7,8,9])

# print(arr[2:5])
# print(arr[-5:-1])
# print(arr[2:7:2])


arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(arr_2d[1:2])
print(arr_2d[:,1])
print(arr_2d[:,1:2])



[[4 5 6]]
[2 5 8]
[[2]
 [5]
 [8]]


In [35]:
unsorted_arr = np.array([4,6,1,2,9,7,3])
np.sort(unsorted_arr)

unsorted_2d_arr = np.array([[7,2],[4,9],[8,1]])
np.sort(unsorted_2d_arr)
np.sort(unsorted_2d_arr, axis=0)


array([[4, 1],
       [7, 2],
       [8, 9]])

In [39]:
numbers = np.array([1,2,3,4,5,6,7,8,9])
print(numbers[numbers % 2 == 0])
print(numbers[numbers > 5])

np.where(numbers > 5)
np.where(numbers > 5, numbers*numbers, numbers)

[2 4 6 8]
[6 7 8 9]


array([ 1,  2,  3,  4,  5, 36, 49, 64, 81])

In [47]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

np.concatenate((arr1,arr2))
arr1[2] = 5
print(arr1)

arr = np.array([[1,2,3,4], [5,6,7,8]])

arr[1][[1,2]] = 100
print(arr)

arr[1] = [10,20,30,40]
print(arr)

arr[:,0] = 10000
print(arr)


[1 2 5]
[[  1   2   3   4]
 [  5 100 100   8]]
[[ 1  2  3  4]
 [10 20 30 40]]
[[10000     2     3     4]
 [10000    20    30    40]]


In [53]:
original_arr = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])
new_col = np.array([[7],[8]])

np.vstack((original_arr,new_row))
np.hstack((original_arr,new_col))

print(original_arr)
np.delete(original_arr)




[[1 2]
 [3 4]]


array([1, 3, 4])

In [66]:
# Data Structure: [restraunt_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000], #restraunt 1
    [2, 120000, 140000, 160000, 190000], #restraunt 2
    [3, 200000, 230000, 260000, 300000], #restraunt 3
    [4, 180000, 210000, 240000, 270000], #restraunt 4
    [5, 160000, 185000, 205000, 230000]  #restraunt 5
])


np.sum(sales_data[:,1])

sum = np.sum(sales_data[:,3], axis=0)
print(sum)

summ = np.sum(sales_data[:,1:], axis=0)
print(summ)


1085000
[ 810000  945000 1085000 1240000]


In [75]:
vector1 = np.array([1,2,3,4])
vector2 = np.array([5,6,7,8])

a = np.add(vector1,vector2)
print(a)
b = np.sum((vector1,vector2))
print(b)

m = np.multiply(vector1,vector2)
print(m)
d = np.divide(vector1,vector2)
print(d)

[ 6  8 10 12]
36
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [77]:
rest_types = np.array(["chinese", "indian", "burger", "pizza"])

a = np.vectorize(str.capitalize)
b = np.vectorize(str.upper)
print(a(rest_types))
print(b(rest_types))

['Chinese' 'Indian' 'Burger' 'Pizza']
['CHINESE' 'INDIAN' 'BURGER' 'PIZZA']


### PANDAS